### ISSUE TITLE
Question about firmware image headers

### ISSUE THREAD

**Issue by benjaoming** [xdarklight/mktplinkfw3#4]
Thanks for your work on this!! I'm new to all this and a bit hesitant to DIY'ing my own serial cable, but I'm also slowly giving up on TP Link support and engineers ability to help me make my device work for my SIP provider.

I have to questions / suggestions...

1) ~I gather that the header that needs to be stripped off when *restoring* original firmware via serial connection is the same header that holds a signature to verify firmware files when uploading and installing through the web interface? Has anyone tried copying and applying this header to an OpenWRT image?~ Nevermind, the question was stupid, I can read clearly from your description that this is exactly what the whole deal here is about :)

2) Can TP Link supply a patched version of their firmware that DOES NOT verify the header of new firmware? This would allow us to release OpenWRT and install through the web interface, right?

Thanks :)
Ben

**Comment by benjaoming** [comment]
Btw. my device in question is the [Archer VR200v](https://wiki.openwrt.org/toh/tp-link/vr200v).

**Comment by xdarklight** [comment]
Hi Ben,

1. OK, you figured that one out already
2. in theory they can: they need to supply an update with a valid header and a firmware inside which does not check the header upon the update after that (in other words: they would need to ship an update with a ``lib/libcmm.so`` that only uses the header for md5sum validation). I'm not sure how likely it is that we'll see something like this though...
3. the VR200v has a bit of an open source problem: while most hardware is supported by open source drivers (+ binary firmware, for example xDSL, telephone is supported but needs devicetree configuration for the VR200v, etc.) none of the wifi chips is supported by open source drivers AFAIK

Regards,
Martin

**Comment by benjaoming** [comment]
Thanks so much for the response!

Regarding the Wireless chip, I found the 5GHz "MT7610EN" chip in other devices that look supported, like Archer C7 AC750 and AC1750 + ASUS RT-AC51U. But seems like a hint that so many components are already troubled.

If the supporters won't  build a new firmware that supports my ISP's SIP settings, I would really wanna try OpenWRT -- but the amount of work regarding serial cable flashing *and* outlook of having to do custom OpenWRT builds is scary. I'll try to ask the supporters to build a firmware w/o key verification nonetheless, always good to make them feel pressured by their users :)
